# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 14. Weiterbildungskurs ÖGW
author: Jakob Schumacher
email: jakob.schumacher@web.de
description: >- # this means to ignore newlines until "baseurl:"
  Meine Mitschriften des 14 Weiterbildungskurs zum Facharzt für öffentliches Gesundheitswesen der Akademie für öffentliches Gesundheitswesen, Düsseldorf
baseurl: "/mitschrift_weiterbildungskurs" # the subpath of your site, e.g. /blog
url: "https://jakobschumacher.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jakobschumacher


# https://github.com/jekyll/jekyll/issues/920#issuecomment-63093764
include: ['_pages']

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      comments: "true"

# Gesetze Collections https://jekyllrb.com/docs/collections/
collections:
  gesetze:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
